baseURL: https://justanothergeek.chdir.org/
disablePathToLower: true
languageCode: en-us
title: Just Another Geek
googleAnalytics: UA-13174242-1
theme: hugo-ink
permalinks:
  post: /:year/:month/:title/
