baseURL: https://justanothergeek.chdir.org/
disablePathToLower: true
languageCode: en-us
title: Just Another Geek
theme: hugo-ink
enableEmoji: true
DisqusShortname: false

permalinks:
  post: /:year/:month/:title/
markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /About
      weight: 2
    - name: What am I doing now
      url: /now
      weight: 3
params:
  subtitle: I am blogging about Information Security since 2003
  featherIconsCDN: true
  mode: auto
  social:
    - name: Twitter
      icon: twitter
      url: https://twitter.com/nbareil/
    - name: Github
      icon: github
      url: https://github.com/nbareil/
    - name: LinkedIn
      icon: linkedin
      url: https://fr.linkedin.com/in/nbareil
    - name: RSS
      icon: rss
      url: /index.xml
